name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Zip build directory
      run: zip -r build.zip build

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_APPLICATION: ${{ secrets.EB_APPLICATION }}
        EB_ENVIRONMENT: ${{ secrets.EB_ENVIRONMENT }}
      run: |
        # Install EB CLI
        pip install --upgrade awsebcli

        # Initialize EB config (if you haven't done it before, else skip)
        # eb init $EB_APPLICATION --region $AWS_REGION --platform "Node.js 22"

        # Deploy with EB CLI
        eb deploy $EB_ENVIRONMENT --staged --verbose
